### ISSUE TITLE
Above the fold Video embed kill PSI scores

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#111]
See this PR https://github.com/hlxsites/uhg-surest/pull/95 and this page

https://landing-pages--uhg-surest--hlxsites.hlx.page/accenture

The above the fold video loads immediately from YT which kills perf. The embed block supports a placeholder image, which should fix it, but the issue is we need to allow authors to provide that placeholder in the context of a column blocks.

One option would be a fragment, but I think we might be able to support it without that.

What I think we should do (but once we start building, there may be other/better ways:
- In the columns block, author makes the image a link to the yt video
- _note: you can't actually link an image in word online. Franklin standard for this is to put the link directly after the image. this gets auto-blocked into an image with a link. We will need to add that functionality, but should be able to easily grab it from another project_
- In the columns block code that detects the embed, that will need to be enhanced so that if the element is an image with a link, then that image gets placed in the embed block.

**Comment by badvision** [comment]
I think this makes sense.  It's easier for authors to understand what they're doing if they can see the http link in the document anyway, so I'll try to pick this up and run with it.
