### ISSUE TITLE
Crawl Issues: Pages Not Found

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#151]
need to evaluate these, add redirects, etc. where appropriate

o	https:www.surest.com/2022-ae
o	https:www.surest.com/404
o	https:www.surest.com/benefit-goals
o	https:www.surest.com/blog/four-ways-to-search-with-the-surest-health-plan
o	https:www.surest.com/blog/how-to-use-the-surest-plan-while-youre-at-your-doctor-visit
o	https:www.surest.com/blog/the-importance-of-preventive-care
o	https:www.surest.com/blog/wellness-guide-ages-76
o	https:www.surest.com/case-study-methodology
o	https:www.surest.com/covid-19-testing-coverage-a-differentiator-for-health-startup-surest
o	https:www.surest.com/flexible-coverage
o	https:www.surest.com/home
o	https:www.surest.com/how-surest-helps-with-mental-health-care
o	https:www.surest.com/minneapolis-health-insurance-startup-bind-benefits-raises-105-million
o	https:www.surest.com/new-approach-to-health-care
o	https:www.surest.com/on-demand-insurance-startup-nabs-venture-capital
o	https:www.surest.com/personalization-inclusivity-in-health-plans
o	https:www.surest.com/prices
o	https:www.surest.com/spotlight-health-startup-bind-benefits-has-big-plans
o	https:www.surest.com/surest-approach-diabetes
o	https:www.surest.com/venture-capitalists-willing-to-fund-insurance-startups
o	https:www.surest.com/what-is-health-equity

**Comment by badvision** [comment]
Published:
- 2022-ae

Added redirect:
- home -> /
- /how-surest-helps-with-mental-health-care -> /blog/how-surest-helps-with-mental-health-care

Seem to work fine:
- 404
- benefit-goals
- /blog/wellness-guide-ages-76
- /case-study-methodology
- /covid-19-testing-coverage-a-differentiator-for-health-startup-surest
- /flexible-coverage
- /minneapolis-health-insurance-startup-bind-benefits-raises-105-million

Cannot find appropriate target page:
- /blog/four-ways-to-search-with-the-surest-health-plan
- /blog/how-to-use-the-surest-plan-while-youre-at-your-doctor-visit
- /blog/the-importance-of-preventive-care

**Comment by badvision** [comment]
@shsteimer see my comments above after going through the list of pages provided.

**Comment by shsteimer** [comment]
I think the last 3 are blogs written after we last did migration. I can migrate them tomorrow.

for everything else, that looks reasonable to me.

**Comment by badvision** [comment]
Did you want to keep this open as a reminder for importing those three blogs?

**Comment by shsteimer** [comment]
yea, I'll import those 3 today then close this, thanks

**Comment by shsteimer** [comment]
this is done. those 3 blog posts are migrated and previewed/published
