### ISSUE TITLE
Crawl Issues: 404s

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#152]
Dawit to provide list so we can evaluate

**Comment by badvision** [comment]
[crawl_overview_baseline_april_2_2023.xlsx](https://github.com/hlxsites/uhg-surest/files/11149448/crawl_overview_baseline_april_2_2023.xlsx)

The crawl overview doesn't provide this, but there is a delta of ~300 urls or so between the old site vs ours.  I suspect a lot of that can be attributed to the heavy use of iframes on the old site, but I don't have an easy way to prove that.

**Comment by shsteimer** [comment]
See spreadsheet https://adobe-dx-support.slack.com/archives/C04P7A3CQ86/p1680652923042409?thread_ts=1680625301.402709&cid=C04P7A3CQ86 for info on referrers for each 404

think these can all be fixed via authoring/redirects. we should work through these and ensure all are handled somehow
