### ISSUE TITLE
JS Errors on Live Site

### ISSUE THREAD

**Issue by trieloff** [hlxsites/uhg-surest#178]
See https://helix-pages.anywhere.run/helix-services/run-query@v2/rum-sources-targets?interval=30&url=www.surest.com&checkpoint=error

https://www.surest.com/get-more?utm_source=flyover_media&utm_medium=display&utm_campaign=broker_employer&utm_id=3&utm_term=&utm_content=employer_retargeting_bottom_line_15s_compad&cntr_auctionId=6434c7dc63ec45cd059c0003
```
failed to load module for header TypeError: Cannot read properties of null (reading 'textContent')
    at Module.decorate (header.js:324:48)
    at async lib-franklin.js:360:15
```

```
https://www.surest.com/scripts/scripts.js
Line 169
```

```
https://www.surest.com/scripts/delayed.js
Line 4
```

**Comment by trieloff** [comment]
```
https://www.surest.com/scripts/scripts.js
Line 169
```

```javascript
const section = h1?.closest('div');
```

@shsteimer this could be an issue with optional chaining on Android, given that the top user agent is `Mozilla/5.0 (Linux; Android 13; SM-S911U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Mobile Safari/537.36`

**Comment by trieloff** [comment]
```
https://www.surest.com/scripts/delayed.js
Line 4
```

```javascript
const placeholders = await fetchPlaceholders();
```

@shsteimer almost 100% sure that this is missing support for https://caniuse.com/mdn-javascript_operators_await_top_level – top UA is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15` (i.e. too major versions too old)

**Comment by shsteimer** [comment]
@trieloff not doubting you are correct, but can you fill me in on why you think "this could be an issue with optional chaining on Android" could be the cause here?

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility all Android browsers support this since 2020, chrome version 80. 

What am I missing?

**Comment by trieloff** [comment]
To be honest, no idea. Caniuse says the browser version should be safe, if optional changing is supported, then the code works or returns `undefined`.

**Comment by trieloff** [comment]
Excactly, `interval` is the number of days from today.
