### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#3]
Note that some pages don't have a hero image, e.g https://www.surest.com/faqs

so auto-blocking code will need to account for that and still create a hero block on those pages.

**Comment by badvision** [comment]
Given the two variations, would it be sufficient to use a has() selector?  Only downside I can see is potential firefox incompatibility for that selector: https://developer.mozilla.org/en-US/docs/Web/CSS/:has 

Another possibility is provided as an alternative using :subject pseudo-classes: https://bugzilla.mozilla.org/show_bug.cgi?id=418039

**Comment by shsteimer** [comment]
I consider that Firefox incompatibility a no go still. We only target modern browsers, so lots of other modern css techniques like container queries are fair game, just a bit early on `:has` I'll have to take a look at the `:subject` thing as that is new to me.

My thinking on the hero is something along the lines of this, but I'm open to other ideas:
1. hero auto-blocking code (If you don't know what this is let me know and I can walk you through it) creates a hero block on every page, which is made up of all elements in the first section
2. hero gets a height/max-height set, and the image if it exists stretches to fill that space (probably with absolute positioning and object: contain)
3. Background color is set, and just lives behind the image, so if the image is there it isn't seen (I'm guessing this is where you think `:has` would be useful). This might require playing with z-indexes, and possible I'm missing something here, but I think it is do-able without using `:has`

**Comment by badvision** [comment]
We might also be able to use sibling or adjacency selectors e.g. apply the style as if there was no image and then add an adjacency rule that overrides the base rule when an image IS present.  https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator
Adjacency selectors are cross-browser compatible I think.

**Comment by shsteimer** [comment]
yea, adjacent sibling, or general sibling selector (`~`) are cross browser and will work.

**Comment by badvision** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/5144198/222015533-123de424-3c08-400d-bb10-4228fa313ae8.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5144198/222015577-2132dd2f-067e-48db-a307-0a81b19de700.png">
