### ISSUE TITLE
Importer does not pick up some tags

### ISSUE THREAD

**Issue by qilto** [hlxsites/uhg-surest#48]
For an example of this, look at the bottom of https://main--uhg-surest--hlxsites.hlx.page/blog/what-to-know-about-surest-when-choosing-health-insurance compared to https://www.surest.com/blog/what-to-know-about-surest-when-choosing-health-insurance. There are some things here like the italicized caption and the footnotes in the sup that are not imported correctly.

**Comment by shsteimer** [comment]
@qilto the captions I think we can update import.js to handle in some way.

the sup in the footnotes I think may be an issue with the importer core when it converts from html => word that it ignores sup/sub tags.
