### ISSUE TITLE
Section Backgrounds

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#5]
I have found at least 4 variants on section backgrounds so far
* grey
* dark purple
* light purple
* image

**Comment by badvision** [comment]
Do the content authors have to determine the backgrounds via metadata or are these backgrounds selected based on the order of sections?  If the authors don't have a reason to decide which background color to use it could simplify things for them.

**Comment by shsteimer** [comment]
I didn't see any rhyme or reason for when certain background colors are used. If we can do su (e.g. section has a given block) then I'm open to that idea, but on my initial pass I was thinking to let authors set it via section metadata.

**Comment by shsteimer** [comment]
mostly fixed in fixed in #42 

background images remain to be done
