### ISSUE TITLE
Hero Issues

### ISSUE THREAD

**Issue by shsteimer** [hlxsites/uhg-surest#55]
Things we ned to look at/address

- heros with dark text (probably author controlled based on background image)
- heroes with CTAs
- here's with p and other non h1 elements
- hero's with various other text styles/colors

**Comment by badvision** [comment]
Dark text example: https://www.surest.com/individuals-families
CTA example: https://www.surest.com/careers
CTA with p elements: 
- https://www.surest.com/contact-us
- https://www.surest.com/lumen-case-study

Do you have examples for various other text styles/colors @shsteimer ?
